# -*- coding: utf-8 -*-
"""Movie correlation project.jpynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZXMym-v6O8m1H4IGX1LaeZHRDzDjsq0Q
"""

# Commented out IPython magic to ensure Python compatibility.
#Import libraries

import pandas as pd
import seaborn as sns
import numpy as np

import matplotlib
import matplotlib.pyplot as plt
plt.style.use('ggplot')
from matplotlib.pyplot import figure

# %matplotlib inline
matplotlib.rcParams['figure.figsize'] = (12,8) # Adjust the configuracion of the plots we will create

# Read in the data

df= pd.read_csv(r'/content/movies.csv')

# Let's look at the data

df.head()

# Let's see if there any missing data

for col in df.columns:
   pct_missing = np.mean(df[col].isnull())
   print('{} - {}%'.format(col,pct_missing))

# Data types for our columns

df.dtypes

# change date type of columns

df['budget']=df['budget'].fillna(0).astype('int64')

df['gross']=df['gross'].fillna(0).astype('int64')

df.head()

# Create correct Year colum

df['released']=df['released'].astype('str').str[:4]

df.head()

df= df.sort_values(by=['gross'], inplace= False, ascending= False)

pd.set_option('display.max_rows', None)

# Drop any duplicates

df.drop_duplicates()

df.head()

# Budget high correlation
# company high correlation

# Scatter plot with budget vs gross

plt.scatter(x=df['budget'], y=df['gross'])
plt.title('Budget vs Gross Earnings')
plt.xlabel('Gross Earnings')
plt.ylabel('Budget for film')
plt.show()

df.head()

# Plot budget vs gross using seaborn

sns.regplot(x='budget', y='gross', data=df, scatter_kws={"color": "red"}, line_kws={"color": "blue"})

#Let's start looking at correlation

df.corr(method= 'pearson',numeric_only=True)

#There's a high correlation between budget and gross

correlation_matrix= df.corr(method= 'pearson',numeric_only=True)

sns.heatmap(correlation_matrix, annot=True)

plt.title('Correlation Matrix for Numeric Features')
plt.xlabel('Movie Features')
plt.ylabel('Movie Features')
plt.show()

#Looks at company

df.head()

df_numerized= df

for col_name in df_numerized.columns:
    if (df_numerized[col_name].dtype == 'object'):
        df_numerized[col_name]=df_numerized[col_name].astype('category')
        df_numerized[col_name]=df_numerized[col_name].cat.codes

df_numerized

correlation_matrix= df_numerized.corr(method= 'pearson',numeric_only=True)

sns.heatmap(correlation_matrix, annot=True)

plt.title('Correlation Matrix for Numeric Features')
plt.xlabel('Movie Features')
plt.ylabel('Movie Features')
plt.show()

df_numerized.corr()

correlation_mat= df_numerized.corr()

corr_pairs= correlation_mat.unstack()

corr_pairs

sorted_pairs= corr_pairs.sort_values()

sorted_pairs

high_corr= sorted_pairs[(sorted_pairs)>0.5]

high_corr

# Votes and budget have the highest correlation to gross earnings

#Company has low correlation